### ISSUE TITLE
why training with ground truth edge map?

### ISSUE THREAD

**Issue by mlyarthur** [rocketappslab/SCA-GAN#1]
It seems that in the code you use ground truth edge map extracted from the target person to perform target person generation.

**Comment by rocketappslab** [comment]
Could you point out the file and lines of code for us to check?

**Comment by rocketappslab** [comment]
> It seems that in the code you use ground truth edge map extracted from the target person to perform target person generation.

Could you point out the file and lines of code for us to check?
