### ISSUE TITLE
Why results using pretrained model are very strange, is there something wrong?

### ISSUE THREAD

**Issue by cfanyyx** [rocketappslab/SCA-GAN#2]
![image](https://user-images.githubusercontent.com/7723243/127831684-98301387-15d5-485e-841c-5bb611018a06.png)
![image](https://user-images.githubusercontent.com/7723243/127831925-e409bd57-1d4e-4c70-9fa8-4663fb1ee712.png)

**Comment by rocketappslab** [comment]
I seems that you cannot successfully load the pre-trained model.
